{% set python_min = "3.10" %}
{% set name = "microsoft-aurora" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_aurora-{{ version }}.tar.gz
  sha256: d3bf371d43f6e396d614394811922966e9a0aa689f5ed4ba1130bef8aa8fd9ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatchling >=1.8.0
    - hatch-vcs
    - pip
    - python {{ python_min }}
  run:
    - einops
    - huggingface_hub
    - numpy
    - python >={{ python_min }}
    - pytorch
    - scipy
    - timm ==0.6.13
  run_constrained:
    - aurora ==999  # avoid clobbering with https://github.com/simpeg/aurora

test:
  imports:
    - aurora
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Implementation of the Aurora model
  license: MIT
  license_file: LICENSE.txt
  home: https://microsoft.github.io/aurora/
  dev_url: https://github.com/microsoft/aurora
  doc_url: https://microsoft.github.io/aurora/api.html
  description: |
    Aurora is a machine learning model that can predict atmospheric variables, such as temperature.
    It is a foundation model, which means that it was first generally trained on a lot of data,
    and then can be adapted to specialised atmospheric forecasting tasks with relatively little data.
    Three such specialised versions are provided: one for medium-resolution weather prediction,
    one for high-resolution weather prediction, and one for air pollution prediction.

extra:
  recipe-maintainers:
    - awvwgk
